FROM python:3.8

ENV PYTHONIOENCODING utf-8

WORKDIR /opt/app

RUN pip install selenium

RUN pip install sqlalchemy

RUN apt-get update && apt-get install -y nano

RUN pip install pandas

RUN pip install mysql-connector-python

#日本語設定
RUN apt-get update && apt-get install -y locales  
RUN sed -i -E 's/# (ja\_JP.UTF-8)/\\1/' /etc/locale.gen && locale-gen  
ENV LANG ja\_JP.UTF-8

